Update

diff --git a/roles/bashrc/files/etc/bash.bashrc.d/bin/pathconfig b/roles/bashrc/files/etc/bash.bashrc.d/bin/pathconfig
--- a/roles/bashrc/files/etc/bash.bashrc.d/bin/pathconfig
+++ b/roles/bashrc/files/etc/bash.bashrc.d/bin/pathconfig
@@ -3,128 +3,147 @@
 THIS="${0##*/}"
 CDIR=$([ -n "${0%/*}" ] && cd "${0%/*}" 2>/dev/null; pwd)
 
+# Name
+THIS="${THIS:-pathconfig}"
+NAME="${THIS%.*}"
+
 ##
-## internal variables
+## Internal variables
 ##
-MODE=
-PRNT=none
+MODE=""
+PRNT=""
 FRCE=0
-TARG=
-NEWP=
-BUFF=
+TARG=""
+NEWP=""
+BUFF=""
+ARGV=""
+XTRC=0
 
 ##
 ## functions
 ##
 
-# check exist path string
-_path_exist() {
-  local _IFS="$IFS"
-  local _ent=""
-  local _ret=1
-  IFS=":"
-  for _ent in $1
-  do
-    _ent="${_ent%/}"
-    [ -z "${2//$_ent}" ] && {
-      _ret=$?; break
-    }
-  done
-  IFS="$_IFS"
-  return $_ret
-}
-
-# path remove
-_path_remove() {
-  local _newp="$1"; shift
-  _newp=${_newp#$1:}
-  _newp=${_newp//:$1:/:}
-  _newp=${_newp%:$1}
-  echo "$_newp"
+# Remove trailing separator
+_remove_trail_slash() {
+  local _lst="${1}"; shift
+  _lst="${_lst//\/\//\/}"; _lst="${_lst%/}"; _lst="${_lst//\/:/:}"
+  echo "${_lst}"
   return $?
 }
 
-# add path string
+# Convert relative path to absolute path
+_relative_to_absolute_path() {
+  local _dir=$(_remove_trail_slash "$1"); shift
+  ( cd "${_dir}" 1>/dev/null 2>&1 &&
+    pwd || echo "${_dir}"; )
+  return $?
+}
+
+# Check exist path string
+_path_exist() {
+  _path_remove "${1}" "${2}" 1>/dev/null 2>&1
+  return $?
+}
+
+# Path remove
+_path_remove() {
+  local _lst=$(_remove_trail_slash "$1"); shift
+  local _dir=$(_relative_to_absolute_path "$1"); shift
+  local newp="${_lst}"
+  newp="${newp#$_dir:}"
+  newp="${newp//:${_dir}:/:}"
+  newp="${newp%:${_dir}}"
+  echo "$newp"
+  [ "${_lst}" != "${newp}" ]
+  return $?
+}
+
+# Add path string
 add_path() {
-  loca newp="$1"; shift
+  local _lst=$(_remove_trail_slash "$1"); shift
+  local _dir=""
+  local newp="${_lst}"
   while [ $# -gt 0 ]
   do
-    [ -e "${1%/}" ] ||
-      { shift; continue; }
-    [ $FRCE -ne 0 ] &&
-      newp=$(_path_remove "$newp" "${1%/}")
-    _path_exist "$newp" "${1%/}" &&
-      { shift; continue; }
-    newp="$newp"`[ -n "$newp" ] && echo ":"`"${1%/}"
-    shift
+    _dir=$(_relative_to_absolute_path "${1}"); shift
+    [ -n "${_dir}" ] || {
+      continue; }
+    [ $FRCE -eq 0 ] || {
+      newp=$(_path_remove "${newp}" "${_dir}"); }
+    _path_exist "$newp" "${_dir}" || {
+      newp="${newp:+${newp}:}${_dir}"; }
   done
   echo "$newp"
-  return 0
+  [ "${_lst}" != "${newp}" ]
+  return $?
 }
 
-# insert path
+# Insert path
 ins_path() {
-  newp="$1"; shift
-  insp=
+  local _lst=$(_remove_trail_slash "$1"); shift
+  local _dir=""
+  local newp="${_lst}"
+  local insp=""
   while [ $# -gt 0 ]
   do
-    [ -e "${1%/}" ] ||
-      { shift; continue; }
-    [ $FRCE -ne 0 ] &&
-      newp=`_path_remove "$newp" "${1%/}"`
-    _path_exist "$newp" "${1%/}" &&
-      { shift; continue; }
-    _path_exist "$insp" "${1%/}" &&
-      { shift; continue; }
-    insp="$insp"`[ -n "$insp" ] && echo ":"`"${1%/}"
-    shift
+    _dir=$(_relative_to_absolute_path "${1}"); shift
+    [ -d "${_dir}" ] || {
+      continue; }
+    [ $FRCE -eq 0 ] || {
+      newp=$(_path_remove "${newp}" "${_dir}"); }
+    _path_exist "$newp" "${_dir}" ||
+    _path_exist "$insp" "${_dir}" || {
+      insp="${insp:+${insp}:}${_dir}"; }
   done
-  [ -n "$insp" -a -n "$newp" ] &&
-    echo "$insp:$newp" ||
-    echo "$insp$newp"
-  unset newp insp
-  return 0
+  [ -n "${insp}" ] && {
+    newp="${insp}${newp+:${newp}}"
+  } || :
+  echo "${newp}"
+  [ "${_lst}" != "${newp}" ]
+  return $?
 }
 
-# delete path
+# Delete path
 del_path() {
-  newp="$1"
-  shift
+  local _lst=$(_remove_trail_slash "$1"); shift
+  local _dir=""
+  local newp="${_lst}"
   while [ $# -gt 0 ]
   do
-    newp=`_path_remove "$newp" "${1%/}"`
-    shift
+    _dir=$(_relative_to_absolute_path "${1}"); shift
+    newp=$(_path_remove "${newp}" "${_dir}")
   done
   echo "$newp"
-  return 0
+  [ "${_lst}" != "${newp}" ]
+  return $?
 }
 
-# modify path environment
+# Modify path environment
 mod_path_env() {
-  _mode="$1"; shift
-  _newp="$1"; shift
-  case $_mode in
-  1) add_path "$_newp" $@ ;;
-  2) ins_path "$_newp" $@ ;;
-  3) del_path "$_newp" $@ ;;
-  *) echo "$_newp" ;;
+  local mode="$1"; shift
+  local list="$1"; shift
+  case $mode in
+  a) add_path "$list" "$@" ;;
+  i) ins_path "$list" "$@" ;;
+  d) del_path "$list" "$@" ;;
+  *) echo "$list" ;;
   esac
-  return 0
+  return $?
 }
 
-# print path list
+# Print path list
 path_list() {
-  _IFS="$IFS"
+  local _IFS="$IFS"
+  local _ent=""
   IFS=":"
-  for _ent in $1; do
-    echo "${_ent%/}"
+  for _ent in ${1}; do
+    _remove_trail_slash "${_ent%/}"
   done
   IFS="$_IFS"
-  unset _IFS _ent
   return 0
 }
 
-# usage
+# Usage
 usage() {
   cat <<__EOF__
 Configuration for PATH environment
@@ -143,77 +162,70 @@ __EOF__
 }
 
 ##
-## parse option(s)
+## Parse option(s)
 ##
-for ARGV in $@
+for ARGV in "$@"
 do
-  case $ARGV in
-  -s|-sh)       PRNT=sh ;;
-  -c|-csh)      PRNT=csh ;;
-  -l|-list)     PRNT=list ;;
-  -f|-force)    FRCE=1 ;;
-  -h|-help)     usage; exit 0 ;;
-  -a|-i|-d)     break ;;
+  case "$ARGV" in
+  -s|-sh|--sh|-c|-csh|--csh|-l|-list|--list)
+    if [ -z "$PRNT" ]
+    then PRNT="${ARGV#*-}"
+    else echo "$THIS: ERROR: Illegal option '$ARGV'" 1>&2; usage; exit 1
+    fi
+    ;;
+  -f|-force|--force) FRCE=1 ;;
+  -h|-help|--help)   usage; exit 0 ;;
+  -x|-debug|--debug) XTRC=1 ;;
+  -a|-i|-d)          break ;;
   -*)
-    echo "$THIS: ERROR: Illegal option '$ARGV'" 1>&2
-    usage
-    exit 1
+    echo "$THIS: ERROR: Illegal option '$ARGV'" 1>&2; usage; exit 1
     ;;
   *)
     ;;
   esac
 done
-unset ARGV
 
 ##
-## first argument
+## First argument
 ##
 if [ -n "$1" ]
-then
-  TARG="$1"
-  NEWP="${!TARG}"
-  shift
-else
-  usage
-  exit 1
+then TARG="$1"; NEWP="${!TARG}"; shift
+else usage; exit 1
 fi
 
+# Prohibits overwriting by redirect and use of undefined variables.
+set -Cu
+
+# Enable trace, verbose
+[ $XTRC -eq 0 ] || {
+  PS4='>(${BASH_SOURCE:-$THIS}:${LINENO:-0})${FUNCNAME:+:$FUNCNAME()}: '
+  export PS4
+  set -xv
+}
+
 ##
-## path manipulation
+## PATH manipulation
 ##
-MODE=0
 while [ $# -gt 0 ]
 do
-  case $1 in
-  -a)
-    NEWP=`mod_path_env $MODE "$NEWP" $BUFF`
-    MODE=1
-    BUFF=
-    ;;
-  -i)
-    NEWP=`mod_path_env $MODE "$NEWP" $BUFF`
-    MODE=2
-    BUFF=
-    ;;
-  -d)
-    NEWP=`mod_path_env $MODE "$NEWP" $BUFF`
-    MODE=3
-    BUFF=
+  case "${1}" in
+  -a|-i|-d)
+    [ -z "$BUFF" ] || {
+    NEWP=$(mod_path_env $MODE "$NEWP" $BUFF); }
+    MODE="${1#*-}"
+    BUFF=""
     ;;
   -*)
     ;;
   *)
-    if [ $MODE -gt 0 ]
+    if [ -n "$MODE" ]
     then
-      BUFF=`[ -n "$BUFF" ] && echo "$BUFF "`"$1"
-      if [ $# -le 1 ]
-      then
-        NEWP=`mod_path_env $MODE "$NEWP" $BUFF`
-      fi
+      BUFF="${BUFF:+$BUFF }${1}"
+      [ $# -le 1 ] && {
+        NEWP=$(mod_path_env $MODE "$NEWP" $BUFF)
+      } || :
     else
-      echo "$THIS: ERROR: Illegal option '$1'" 1>&2
-      usage
-      exit 1
+      echo "$THIS: ERROR: Illegal option '$1'" 1>&2; usage; exit 1
     fi
     ;;
   esac
@@ -221,21 +233,13 @@ do
 done
 
 ##
-## print new value
+## Print new value
 ##
-case $PRNT in
-sh)
-  echo "$TARG="'"'"$NEWP"'"'"; export $TARG"
-  ;;
-csh)
-  echo "setenv $TARG "'"'"$NEWP"'"'
-  ;;
-list)
-  path_list $NEWP
-  ;;
-*)
-  echo "$NEWP"
-  ;;
+case "$PRNT" in
+s|sh)   echo "$TARG="'"'"$NEWP"'"'"; export $TARG" ;;
+c|csh)  echo "setenv $TARG "'"'"$NEWP"'"' ;;
+l|list) path_list $NEWP ;;
+*)      echo "$NEWP" ;;
 esac
 
 # end of shell
